format: makefile
data:
  MPICOMM: nompicomm
  GRAVITY: nogravity
  FORCING: noforcing
  ENTROPY: entropy
  MAGNETIC: nomagnetic
  HYDRO: hydro
  DENSITY: density
  VISCOSITY: viscosity
  SHOCK: shock_highorder
  POWER: nopower_spectrum
